branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# ØKP4 protocol changelog"
  - - "semantic-release-replace-plugin"
    - replacements:
        - files: [version]
          from: ^.+$
          to: ${nextRelease.version}
          countMatches: true
          results:
            - file: version
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/exec"
    - prepareCmd: |
        major_version=$(cat version | cut -d. -f1)
        if [ $major_version -gt 1 ]; then
            module_name=$(go mod edit -json | jq -r '.Module.Path')
            module_name_unversioned=$(echo ${module_name} | sed -E 's|/v[0-9]+$||')
            module_name_versioned="${module_name_unversioned}/v${major_version}"
            echo "🔬 major version detected, updating module path to ${module_name_versioned}"

            go mod edit -module "${module_name_versioned}"
            echo "✅ module name updated to ${module_name_versioned} in go.mod"

            if [ "$(uname)" = "Darwin" ]; then
              find . -type f -name "*.go" -exec \
                sed -i '' "s|\"${module_name}|\"${module_name_versioned}|g" {} \;
            else
              find . -type f -name "*.go" -exec \
                sed -i "s|\"${module_name}|\"${module_name_versioned}|g" {} \;
            fi
            echo "✅ packages updated to ${module_name_versioned} in source files"

            echo "🧹 cleaning up go.sum"
            go mod tidy
        else
            echo "🙅version is not greater than 1, no need to update module path"
        fi
  - - "@semantic-release/exec"
    - prepareCmd: |
        make release-assets
  - - "@semantic-release/github"
    - assets:
        - path: "./target/release/okp4d-*-linux-amd64"
        - path: "./target/release/okp4d-*-linux-amd64.tar.gz"
        - path: "./target/release/okp4d-*-linux-arm64"
        - path: "./target/release/okp4d-*-linux-arm64.tar.gz"
        - path: "./target/release/sha256sum.txt"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - version
        - go.mod
        - go.sum
        - "**/*.go"
      message: "chore(release): perform release ${nextRelease.version}"
