chains:
  - name: axone-1
    type: custom
    numValidators: 4
    image: anmol1696/axoned:latest
    home: /root/.axoned
    binary: axoned
    prefix: axone
    denom: uknow
    coins: 100000000000000uknow
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/axone-protocol/axoned
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8007
    resources:
      cpu: 1
      memory: 2Gi
  - name: gaia-1
    type: cosmos
    numValidators: 4
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003
    resources:
      cpu: 1
      memory: 2Gi

relayers:
  - name: axone-gaia
    type: hermes
    replicas: 1
    chains:
      - axone-1
      - gaia-1
    resources:
      cpu: 1
      memory: 2Gi

registry:
  enabled: true
  ports:
    rest: 8081

explorers:
  enabled: true
  ports:
    rest: 8080
