name: Update Draft docs

on:
  push:
    branches: [ main ]

jobs:
  update-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Update modules docs repository
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/okp4/docs/actions/workflows/39152549/dispatches'
          method: 'POST'
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OKP4_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "version": "main",
                "repository": "${{github.repository}}",
                "section": "modules",
                "docs_directory": "docs/proto/*",
                "draft": "true"
              }
            }

      - name: Update commands docs repository
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/okp4/docs/actions/workflows/39152549/dispatches'
          method: 'POST'
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OKP4_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "version": "main",
                "repository": "${{github.repository}}",
                "section": "commands",
                "docs_directory": "docs/command/*",
                "draft": "true"
              }
            }

      - name: Update predicates docs repository
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/okp4/docs/actions/workflows/39152549/dispatches'
          method: 'POST'
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OKP4_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "version": "main",
                "repository": "${{github.repository}}",
                "section": "predicates",
                "docs_directory": "docs/predicate/*",
                "draft": "true"
              }
            }
